# Generated by Django 5.2.9 on 2026-04-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0031_auto_20250904_1125"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("time_limit", models.TimeField()),
                ("weekday_limit", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("weekday_service", models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="ReservationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meal_reservation.mealmodel"
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.responsiblemodel"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["date"], name="meal_reserv_date_27ad34_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "responsible"), name="meal_by_day_by_person"
                    )
                ],
            },
        ),
    ]
