# Generated by Django 5.2.9 on 2026-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_reservation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationmodel",
            name="comment",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
